server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 30

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  datasource:
    url: jdbc:mariadb://localhost:3306/greendb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: green1234
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    "[org.springframework.web]": DEBUG
    "[org.hibernate]": DEBUG
